// GENERATED by tool/build_levels.py — edit that file instead.

import 'level.dart';

final List<LevelData> kLevels = [
  LevelData(
    id: 'feed',
    name: 'Il Feed',
    subtitle: 'Scrolla verso il successo',
    theme: LevelTheme.feed,
    parTime: 120,
    map: '''
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
            oo                                                                                            oooo            oooo              
           ?B?B                        ooo                                 ?B?                ooo         B?BB           BBBBB              
                                      =====                B                             ooo  ===                       BB                  
                        ooo                               BB                             ===                           BBB                  
  P   ooo           n                         n      c   BBB     K       n      n ooo                   c     n       BBBB          F       
###############################   ##########################   ########################           ##########################################
###############################   ##########################   ########################           ##########################################
''',
  ),
  LevelData(
    id: 'comments',
    name: 'Sezione Commenti',
    subtitle: 'Attenti agli Hater',
    theme: LevelTheme.comments,
    parTime: 150,
    map: '''
                                                                                                                                                                
                                                                                                                                                                
                                                                                                                                                                
                                                                                                                                                                
                                                                                                                                                                
                                                                                                                                                                
                                                                                              oooo                                                              
                                         ooooo                                  oooo          ====              ooo                                 oooo        
            oooo               ???       =====                            B??B  ====                n           ===         ?                      B            
            ====                                       ooooo                               ##      ====                                           BB            
                                                      #######                              ##                                                    BBB            
  P      h        ^^  b             n   h ^^^   c     #######     K     b     h ^^^^   c   ##              ^^^h     b   n          K    c   h   BBBB      F     
#########################   #######################   #######   #############################           ######################   ###############################
#########################   #######################   #######   #############################           ######################   ###############################
''',
  ),
  LevelData(
    id: 'server',
    name: 'Il Server',
    subtitle: 'Sconfiggi L\'Algoritmo',
    theme: LevelTheme.server,
    parTime: 180,
    map: '''
                                                                                                                                                       G                  
                                                                                                                                                       G                  
                                                                                                                                                       G                  
                                                                                                                                                       G                  
                                                                                                                                                       G                  
                                                                                                                                                       G                  
                                                                                                                               ======                  G                  
          oooo                                ooo                    c                oooo                                                             G                  
          ====                          B??B  ===                   ===  ooo          ====              ??          ====                    ====       G                  
                                                               ooo       ===                                                                           G                  
                          ^^                                   ===           ==                                                                        G   oooooo         
  P     n   c   h       #######      b      h ^^^ b     K                           h     n ^^^b    h       K                          A               G            F     
#####################   #######   ###########################                   ##########################################################################################
#####################   #######   ###########################                   ##########################################################################################
''',
  ),
];
